version: 2.1

orbs:
  node: circleci/node@5.1.0
  aws-ecr: circleci/aws-ecr@7.3.0

jobs:
  test:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages
        override-ci-command: npm install
      - run:
          command: npm run test
workflows:
  test-build-push-image:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          repo: devops-upskill-api
          tag: '1.$CIRCLE_BUILD_NUM'
          requires:
            - "test"